In [3]:
import pandas as pd

In [4]:
train_df = pd.read_csv("data/fraudTrain.csv")
test_df = pd.read_csv("data/fraudTest.csv")

print(train_df.shape)
print(test_df.shape)

(1296675, 23)
(555719, 23)

In [7]:
train_df['trans_date_trans_time'] = pd.to_datetime(
    train_df['trans_date_trans_time']
)

test_df['trans_date_trans_time'] = pd.to_datetime(
    test_df['trans_date_trans_time']
)

In [8]:
train_df['transaction_hour'] = (
    train_df['trans_date_trans_time'].dt.hour
)

train_df['transaction_day'] = (
    train_df['trans_date_trans_time'].dt.day
)

train_df['transaction_month'] = (
    train_df['trans_date_trans_time'].dt.month
)

train_df['transaction_dayofweek_num'] = (
    train_df['trans_date_trans_time'].dt.dayofweek
)

In [9]:
test_df['transaction_hour'] = (
    test_df['trans_date_trans_time'].dt.hour
)

test_df['transaction_day'] = (
    test_df['trans_date_trans_time'].dt.day
)

test_df['transaction_month'] = (
    test_df['trans_date_trans_time'].dt.month
)

test_df['transaction_dayofweek_num'] = (
    test_df['trans_date_trans_time'].dt.dayofweek
)

In [10]:
train_df['is_weekend'] = (
    train_df['transaction_dayofweek_num'] >= 5
).astype(int)

In [12]:
import numpy as np

In [13]:
train_df['amt_log'] = np.log1p(train_df['amt'])

In [14]:
import pandas as pd
import numpy as np

In [15]:
train_df[['amt', 'amt_log']].head()

      amt   amt_log
0    4.97  1.786747
1  107.23  4.684259
2  220.11  5.398660
3   45.00  3.828641
4   41.96  3.760269

In [18]:
categorical_cols = train_df.select_dtypes(
    include=['str']
).columns

print(categorical_cols)

Index(['merchant', 'category', 'first', 'last', 'gender', 'street', 'city',
       'state', 'job', 'dob', 'trans_num'],
      dtype='str')

In [20]:
numeric_cols = train_df.select_dtypes(
    include=np.number
).columns

print(numeric_cols)

Index(['Unnamed: 0', 'cc_num', 'amt', 'zip', 'lat', 'long', 'city_pop',
       'unix_time', 'merch_lat', 'merch_long', 'is_fraud', 'transaction_hour',
       'transaction_day', 'transaction_month', 'transaction_dayofweek_num',
       'is_weekend', 'amt_log'],
      dtype='str')

In [21]:
print(
    train_df.isnull().sum().sort_values(ascending=False).head(10)
)

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
dtype: int64

In [22]:
print("Final Dataset Shape:", train_df.shape)

Final Dataset Shape: (1296675, 29)

In [23]:
new_features = [
    'transaction_hour',
    'transaction_day',
    'transaction_month',
    'transaction_dayofweek_num',
    'is_weekend',
    'amt_log'
]

train_df[new_features].head()

,transaction_hour,transaction_day,transaction_month,transaction_dayofweek_num,is_weekend,amt_log
0,0,1,1,1,0,1.786747
1,0,1,1,1,0,4.684259
2,0,1,1,1,0,5.398660
3,0,1,1,1,0,3.828641
4,0,1,1,1,0,3.760269